### ISSUE TITLE
Merge projects for full experience

### ISSUE THREAD

**Issue by Schmidsfeld** [TheWicklowWolf/Syncify#1]
I came here after trying (and also commenting) on Lidify.

You have some projects  that have a significant overlapp in what they do and how they are coded:

- Syncify
- Lidify
- SpotTube
- LidaTube (not spottify but also great)

These all extend lidarr using spottyfy and making a migration to a selfhosted service feasable.
At the moment these are each providing one small service. But it would be great to have the all in one place. 

Sync Spottyfy playlist and download it into Lidarr.
Discover new similar artists in Lidarr (and also downloading them).

I thus propose that these Projects are Merged into a new overall project that is a one stop shop for Lidarr extension.
The Project could be named Spottarr to make it part of the *arr family and clearyfy the purpose of it. 
Also it should use another port than the often used 5000 - I suggest 6868 - like in my pull request for Lidify.

Edit:
Ofcourse I am willing to help/contribute,  bit I think the project should be initially created and merged by you as the original author.

**Comment by TheWicklowWolf** [comment]
Spottarr is a great name, but for me this project is not on the agenda at the minute. 
The functionality of organizing each section into tabs (if they were combined) isn't significantly different from having them on separate links.
Additionally, the potential size and computational savings are not substantial enough to warrant further consideration at this time.

 However, I'll open a **Spotarr** repository as a placeholder for future reference.
